apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: folder-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ $.Values.storage.storageClass }}
  volumeMode: Filesystem
